#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking for errors before pushing..."

# TypeScript check without emitting files
npx tsc --noEmit 

# Optional: Run linting
npm run prettier



echo "Code passed all checks! Pushing..."
